apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: custom-metrics-apiserver
  name: custom-metrics-apiserver
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-metrics-apiserver
  template:
    metadata:
      labels:
        app: custom-metrics-apiserver
      name: custom-metrics-apiserver
    spec:
      serviceAccountName: custom-metrics-apiserver
      containers:
      - name: custom-metrics-apiserver
        image: huxl/k8s-prometheus-adapter-amd64:v0.2.0
        imagePullPolicy: Always
        args:
        - /adapter
        - --secure-port=6443
        - --tls-cert-file=/var/run/serving-cert/serving.crt
        - --tls-private-key-file=/var/run/serving-cert/serving.key
        - --logtostderr=true
        - --prometheus-url=https://monitoring-prometheus:9090
        - --prometheus-cacert=/opt/ibm/monitoring/ca-certs/ca.pem
        - --prometheus-key=/opt/ibm/monitoring/certs/tls.key
        - --prometheus-cert=/opt/ibm/monitoring/certs/tls.crt
        - --prometheus-insecure=true
        - --metrics-relist-interval=30s
        - --rate-interval=5m
        - --v=10
        ports:
        - containerPort: 6443
        volumeMounts:
        - mountPath: /var/run/serving-cert
          name: volume-serving-cert
          readOnly: true
        - mountPath: "/opt/ibm/monitoring/certs"
          name: monitoring-client-certs
        - mountPath: "/opt/ibm/monitoring/ca-certs"
          name: monitoring-ca-cert
      volumes:
      - name: volume-serving-cert
        secret:
          secretName: cm-adapter-serving-certs
      - name: monitoring-client-certs
        secret:
          secretName: monitoring-client-certs
      - name: monitoring-ca-cert
        secret:
          secretName: monitoring-ca-cert
